// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMovies(filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3392700998, filePaths);
}

export function CancelProcessing(): $CancellablePromise<void> {
    return $Call.ByID(2842299945);
}

export function ClearMovies(): $CancellablePromise<void> {
    return $Call.ByID(2972937796);
}

export function GenerateResult(): $CancellablePromise<string> {
    return $Call.ByID(2136589038);
}

export function GenerateResultForMovie(movieID: string): $CancellablePromise<string> {
    return $Call.ByID(3733019759, movieID);
}

export function GetDefaultTemplate(): $CancellablePromise<string> {
    return $Call.ByID(1750268687);
}

export function GetExpandedFilePaths(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(572084405, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Settings management
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2528037945).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetState(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1770976393).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Template management
 */
export function GetTemplate(): $CancellablePromise<string> {
    return $Call.ByID(2486279326);
}

export function RemoveMovie(id: string): $CancellablePromise<void> {
    return $Call.ByID(2848711252, id);
}

export function ReorderMovies(newOrder: string[]): $CancellablePromise<void> {
    return $Call.ByID(1964823934, newOrder);
}

export function ResetMovieStatuses(): $CancellablePromise<void> {
    return $Call.ByID(1291166359);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1525544291, app);
}

export function SetTemplate(template: string): $CancellablePromise<void> {
    return $Call.ByID(347943698, template);
}

export function StartProcessing(): $CancellablePromise<void> {
    return $Call.ByID(2555650935);
}

export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1698034644, settings);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.AppSettings.createFrom;
const $$createType2 = $models.AppState.createFrom;
