// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMovies(filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1713676999, filePaths);
}

export function CancelProcessing(): $CancellablePromise<void> {
    return $Call.ByID(3064429438);
}

export function ClearMovies(): $CancellablePromise<void> {
    return $Call.ByID(3171510169);
}

export function GenerateResult(): $CancellablePromise<string> {
    return $Call.ByID(3657805917);
}

export function GenerateResultForMovie(movieID: string): $CancellablePromise<string> {
    return $Call.ByID(2061823948, movieID);
}

export function GetDefaultTemplate(): $CancellablePromise<string> {
    return $Call.ByID(2595592496);
}

export function GetExpandedFilePaths(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(973813346, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Settings management
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3032029384).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetState(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(2500004534).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Template management
 */
export function GetTemplate(): $CancellablePromise<string> {
    return $Call.ByID(3477835723);
}

export function RemoveMovie(id: string): $CancellablePromise<void> {
    return $Call.ByID(1918132965, id);
}

export function ReorderMovies(newOrder: string[]): $CancellablePromise<void> {
    return $Call.ByID(496840875, newOrder);
}

export function ResetMovieStatuses(): $CancellablePromise<void> {
    return $Call.ByID(3200334824);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3554972488, app);
}

export function SetTemplate(template: string): $CancellablePromise<void> {
    return $Call.ByID(832888415, template);
}

export function StartProcessing(): $CancellablePromise<void> {
    return $Call.ByID(957831002);
}

export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1370010191, settings);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.AppSettings.createFrom;
const $$createType2 = $models.AppState.createFrom;
