// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings represents application settings
 */
export class AppSettings {
    "language": string;
    "convertToGb": boolean;
    "centerAlign": boolean;
    "acceptOnlyLinks": boolean;
    "hideEmpty": boolean;
    "uiFontSize": number;
    "listFontSize": number;
    "textFontSize": number;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("convertToGb" in $$source)) {
            this["convertToGb"] = false;
        }
        if (!("centerAlign" in $$source)) {
            this["centerAlign"] = false;
        }
        if (!("acceptOnlyLinks" in $$source)) {
            this["acceptOnlyLinks"] = false;
        }
        if (!("hideEmpty" in $$source)) {
            this["hideEmpty"] = false;
        }
        if (!("uiFontSize" in $$source)) {
            this["uiFontSize"] = 0;
        }
        if (!("listFontSize" in $$source)) {
            this["listFontSize"] = 0;
        }
        if (!("textFontSize" in $$source)) {
            this["textFontSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * LinkProcessResult represents the result of link processing
 */
export class LinkProcessResult {
    "originalLinks": string[];
    "processedLinks": string[];
    "errors": string[];

    /** Creates a new LinkProcessResult instance. */
    constructor($$source: Partial<LinkProcessResult> = {}) {
        if (!("originalLinks" in $$source)) {
            this["originalLinks"] = [];
        }
        if (!("processedLinks" in $$source)) {
            this["processedLinks"] = [];
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkProcessResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkProcessResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("originalLinks" in $$parsedSource) {
            $$parsedSource["originalLinks"] = $$createField0_0($$parsedSource["originalLinks"]);
        }
        if ("processedLinks" in $$parsedSource) {
            $$parsedSource["processedLinks"] = $$createField1_0($$parsedSource["processedLinks"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new LinkProcessResult($$parsedSource as Partial<LinkProcessResult>);
    }
}

/**
 * Movie represents a media file with its metadata
 */
export class Movie {
    "id": number;
    "fileName": string;
    "filePath": string;
    "fileSize": string;
    "fileSizeBytes": number;
    "duration": string;
    "width": string;
    "height": string;
    "screenListURL": string;
    "params": { [_: string]: string };

    /** Creates a new Movie instance. */
    constructor($$source: Partial<Movie> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = "";
        }
        if (!("fileSizeBytes" in $$source)) {
            this["fileSizeBytes"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = "";
        }
        if (!("height" in $$source)) {
            this["height"] = "";
        }
        if (!("screenListURL" in $$source)) {
            this["screenListURL"] = "";
        }
        if (!("params" in $$source)) {
            this["params"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Movie instance from a string or object.
     */
    static createFrom($$source: any = {}): Movie {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        return new Movie($$parsedSource as Partial<Movie>);
    }
}

/**
 * ProcessProgress represents file processing progress
 */
export class ProcessProgress {
    "current": number;
    "total": number;
    "fileName": string;
    "message": string;
    "completed": boolean;
    "error"?: string;

    /** Creates a new ProcessProgress instance. */
    constructor($$source: Partial<ProcessProgress> = {}) {
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessProgress($$parsedSource as Partial<ProcessProgress>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
