// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMovie(movie: $models.Movie): $CancellablePromise<void> {
    return $Call.ByID(2167188870, movie);
}

/**
 * AddPendingFiles adds files to the list with pending status
 */
export function AddPendingFiles(filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3518933892, filePaths);
}

export function ClearMovies(): $CancellablePromise<void> {
    return $Call.ByID(3366575601);
}

export function EmitProgress(progress: $models.ProcessProgress): $CancellablePromise<void> {
    return $Call.ByID(2779484171, progress);
}

/**
 * GenerateResult generates the formatted spoiler list for all movies
 */
export function GenerateResult(): $CancellablePromise<string> {
    return $Call.ByID(1858085317);
}

/**
 * GenerateResultForMovie generates spoiler for a single movie
 */
export function GenerateResultForMovie(movieID: number): $CancellablePromise<string> {
    return $Call.ByID(2420383732, movieID);
}

export function GetExpandedFilePaths(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(2612523930, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetMovies(): $CancellablePromise<$models.Movie[]> {
    return $Call.ByID(1376886268).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Settings management
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3737918080).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Template management
 */
export function GetTemplate(): $CancellablePromise<string> {
    return $Call.ByID(841079811);
}

export function ProcessFiles(filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(768775415, filePaths);
}

export function ProcessFilesAsync(filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(4139121497, filePaths);
}

export function RemoveMovie(id: number): $CancellablePromise<void> {
    return $Call.ByID(2824633037, id);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(671908240, app);
}

export function SetTemplate(template: string): $CancellablePromise<void> {
    return $Call.ByID(2381016119, template);
}

export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(724887735, settings);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.Movie.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.AppSettings.createFrom;
