// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMovies(filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1314248879, filePaths);
}

export function CancelProcessing(): $CancellablePromise<void> {
    return $Call.ByID(1786494294);
}

export function ClearMovies(): $CancellablePromise<void> {
    return $Call.ByID(3366575601);
}

export function GenerateResult(): $CancellablePromise<string> {
    return $Call.ByID(1858085317);
}

export function GenerateResultForMovie(movieID: string): $CancellablePromise<string> {
    return $Call.ByID(2420383732, movieID);
}

export function GetDefaultTemplate(): $CancellablePromise<string> {
    return $Call.ByID(202669800);
}

export function GetExpandedFilePaths(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(2612523930, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Settings management
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3737918080).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetState(): $CancellablePromise<$models.AppState> {
    return $Call.ByID(1461037886).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Template management
 */
export function GetTemplate(): $CancellablePromise<string> {
    return $Call.ByID(841079811);
}

export function RemoveMovie(id: string): $CancellablePromise<void> {
    return $Call.ByID(2824633037, id);
}

export function ReorderMovies(newOrder: string[]): $CancellablePromise<void> {
    return $Call.ByID(3360971939, newOrder);
}

export function ResetMovieStatuses(): $CancellablePromise<void> {
    return $Call.ByID(2773813152);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(671908240, app);
}

export function SetTemplate(template: string): $CancellablePromise<void> {
    return $Call.ByID(2381016119, template);
}

export function StartProcessing(): $CancellablePromise<void> {
    return $Call.ByID(4006642018);
}

export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(724887735, settings);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.AppSettings.createFrom;
const $$createType2 = $models.AppState.createFrom;
